import uniqid from 'uniqid';

export const gameData = [
    {card: "arcanine", count: 0, id: uniqid()},
    {card: "bulbasaur", count: 0, id: uniqid()},
    {card: "charmander", count: 0, id: uniqid()},
    {card: "ditto", count: 0, id: uniqid()},
    {card: "dragonite", count: 0, id: uniqid()},
    {card: "eevee", count: 0, id: uniqid()},
    {card: "gengar", count: 0, id: uniqid()},
    {card: "gyarados", count: 0, id: uniqid()},
    {card: "jigglypuff", count: 0, id: uniqid()},
    {card: "kadabra", count: 0, id: uniqid()},
    {card: "lapras", count: 0, id: uniqid()},
    {card: "machamp", count: 0, id: uniqid()},
    {card: "marowak", count: 0, id: uniqid()},
    {card: "meowth", count: 0, id: uniqid()},
    {card: "mew", count: 0, id: uniqid()},
    {card: "ninetales", count: 0, id: uniqid()},
    {card: "onix", count: 0, id: uniqid()},
    {card: "pidgeotto", count: 0, id: uniqid()},
    {card: "pikachu", count: 0, id: uniqid()},
    {card: "poliwrath", count: 0, id: uniqid()},
    {card: "ponyta", count: 0, id: uniqid()},
    {card: "scyther", count: 0, id: uniqid()},
    {card: "snorlax", count: 0, id: uniqid()},
    {card: "squirtle", count: 0, id: uniqid()},
    {card: "zapdos", count: 0, id: uniqid()},
]