export const gameData = [
    { card: "arcanine", count: 0 },
    { card: "bulbasaur", count: 0 },
    { card: "charmander", count: 0 },
    { card: "ditto", count: 0 },
    { card: "dragonite", count: 0 },
    { card: "eevee", count: 0 },
    { card: "gengar", count: 0 },
    { card: "gyarados", count: 0 },
    { card: "jigglypuff", count: 0 },
    { card: "kadabra", count: 0 },
    { card: "lapras", count: 0 },
    { card: "machamp", count: 0 },
    { card: "marowak", count: 0 },
    { card: "meowth", count: 0 },
    { card: "mew", count: 0 },
    { card: "ninetales", count: 0 },
    { card: "onix", count: 0 },
    { card: "pidgeotto", count: 0 },
    { card: "pikachu", count: 0 },
    { card: "poliwrath", count: 0 },
    { card: "ponyta", count: 0 },
    { card: "scyther", count: 0 },
    { card: "snorlax", count: 0 },
    { card: "squirtle", count: 0 },
  ];
  